// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEntropyEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddEntropyEvent'](arg1, arg2, arg3);
}

export function AddFiles() {
  return window['go']['main']['App']['AddFiles']();
}

export function CreateVault(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateVault'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteVault() {
  return window['go']['main']['App']['DeleteVault']();
}

export function ExtractFile(arg1) {
  return window['go']['main']['App']['ExtractFile'](arg1);
}

export function GetCategoryStats() {
  return window['go']['main']['App']['GetCategoryStats']();
}

export function GetEntropyProgress() {
  return window['go']['main']['App']['GetEntropyProgress']();
}

export function GetHomeDirectory() {
  return window['go']['main']['App']['GetHomeDirectory']();
}

export function GetRecoveryMnemonic() {
  return window['go']['main']['App']['GetRecoveryMnemonic']();
}

export function GetVaultStats() {
  return window['go']['main']['App']['GetVaultStats']();
}

export function IsEntropyComplete() {
  return window['go']['main']['App']['IsEntropyComplete']();
}

export function IsVaultUnlocked() {
  return window['go']['main']['App']['IsVaultUnlocked']();
}

export function ListFiles() {
  return window['go']['main']['App']['ListFiles']();
}

export function LockVault() {
  return window['go']['main']['App']['LockVault']();
}

export function RecoverVaultWithSeed(arg1, arg2) {
  return window['go']['main']['App']['RecoverVaultWithSeed'](arg1, arg2);
}

export function RequestRecoveryMnemonic(arg1, arg2) {
  return window['go']['main']['App']['RequestRecoveryMnemonic'](arg1, arg2);
}

export function SelectVaultDirectory() {
  return window['go']['main']['App']['SelectVaultDirectory']();
}

export function SelectVaultFile() {
  return window['go']['main']['App']['SelectVaultFile']();
}

export function StartEntropyCollection() {
  return window['go']['main']['App']['StartEntropyCollection']();
}

export function UnlockVault(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UnlockVault'](arg1, arg2, arg3, arg4);
}

export function VaultExistsAtPath(arg1) {
  return window['go']['main']['App']['VaultExistsAtPath'](arg1);
}
