// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddEntropyEvent(arg1:number,arg2:number,arg3:number):Promise<void>;

export function AddFiles():Promise<void>;

export function CreateVault(arg1:string,arg2:number,arg3:number,arg4:Array<string>,arg5:string):Promise<string>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteVault():Promise<void>;

export function ExtractFile(arg1:string):Promise<void>;

export function GetCategoryStats():Promise<Record<string, number>>;

export function GetEntropyProgress():Promise<number>;

export function GetHomeDirectory():Promise<string>;

export function GetRecoveryMnemonic():Promise<Array<string>>;

export function GetVaultStats():Promise<main.VaultStats>;

export function IsEntropyComplete():Promise<boolean>;

export function IsVaultUnlocked():Promise<boolean>;

export function ListFiles():Promise<Array<main.FileInfo>>;

export function LockVault():Promise<void>;

export function RecoverVaultWithSeed(arg1:Array<string>,arg2:string):Promise<string>;

export function RequestRecoveryMnemonic(arg1:string,arg2:number):Promise<Array<string>>;

export function SelectVaultDirectory():Promise<string>;

export function SelectVaultFile():Promise<string>;

export function StartEntropyCollection():Promise<void>;

export function UnlockVault(arg1:string,arg2:number,arg3:Array<string>,arg4:string):Promise<void>;

export function VaultExistsAtPath(arg1:string):Promise<boolean>;
